#!/bin/bash
if [ -z "$BASH_VERSION" ];then
	echo "It appears you are using dash or sh, you must use bash or rbash to run this script"
	exit
fi
here=$(dirname $0)
echo "Need a couple dependencies"
sudo apt-get install -y -m curl libnotify-bin
if [[ ! -f /usr/bin/curl || ! -f /usr/bin/php || ! -f /usr/bin/notify-send ]];then
	echo "You did not install the dependencies"
	echo "You need have the curl, php, and notify-send commands available for use"
	exit
fi
chmod +x $here/KernelUpdate*
sudo cp $here/KernelUpdate* /usr/local/bin/
echo -e "Install Complete\n"
